version: '2.19.1'
services:
  dev-db:
    image: postgres:16
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: bookmark-db
    networks:
      - bookmark-api
networks:
  bookmark-api:
